### ISSUE TITLE
Crash on https://doc.deno.land/https://esm.sh/preact/~/createElement

### ISSUE THREAD

**Issue by lucacasonato** [denoland/docland#31]
```
[error] Error: Not every node of kind "function".

    at assertAll (file:///mnt/starship/Projects/github.com/denoland/docland/components/doc.tsx:37:11)
    at CodeBlock (file:///mnt/starship/Projects/github.com/denoland/docland/components/doc.tsx:129:5)
    at renderFunctionalComponent (https://deno.land/x/nano_jsx@v0.0.21/core.ts:164:18)
    at _render (https://deno.land/x/nano_jsx@v0.0.21/core.ts:138:70)
    at https://deno.land/x/nano_jsx@v0.0.21/core.ts:48:17
    at Array.forEach (<anonymous>)
    at appendChildren (https://deno.land/x/nano_jsx@v0.0.21/core.ts:43:12)
    at h (https://deno.land/x/nano_jsx@v0.0.21/core.ts:255:3)
    at DocPage (file:///mnt/starship/Projects/github.com/denoland/docland/components/doc.tsx:273:25)
    at renderFunctionalComponent (https://deno.land/x/nano_jsx@v0.0.21/core.ts:164:18)
```

**Comment by kitsonk** [comment]
Ok, I know what the issue is, just unexpected.  Thanks for the repo.
